import './globals.css'
import { Inter } from 'next/font/google'
import { Montserrat } from 'next/font/google'

const montserrat = Montserrat({
  weight: ["400" , "700"],
  subsets: ["latin"],
  variable: "--font-montserrat",
})



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  // title: 'Create Next App',
  title: 'Next 13 Experiment',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={montserrat.className}>
      <nav>
        <ul>
          <li>Logo</li>
          <li>Home</li>
          <li>About</li>
          <li>LogIn</li>
          <li>SignIn</li>

        </ul>
      </nav>
      {children}</body>
    </html>
  )
}
